media: media  # serve uploads from /media, stored in media/

content:
  - name: posts
    label: "Blog Posts"
    type: collection
    path: "_posts"            
    create: true
    view:
      fields: [title, date, author]
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: author
        label: Author
        type: string
      - name: summary
        label: Summary
        type: text
      - name: coverImage
        label: Cover Image
        type: image
      - name: content
        label: Body
        type: rich-text

  - name: siteConfig
    label: "Site Configuration"
    type: file
    path: "src/_data/site.json"
    fields:
      - name: title
        label: Website Title
        type: string
      - name: description
        label: Site Description
        type: text
      - name: url
        label: Site URL
        type: string
      - name: cover
        label: Preview Image
        type: image
