{
  "siteName": "upsc",
  "repo": "https://github.com/CoderBot01/UPSC",
  "branch": "main",
  "mediaFolder": "public/images/uploads",
  "publicFolder": "/images/uploads",
  "collections": [
    {
      "name": "blog",
      "label": "Blog Posts",
      "folder": "content/blog",
      "create": true,
      "fields": [
        { "name": "title", "label": "Title", "widget": "string" },
        { "name": "date", "label": "Date", "widget": "datetime" },
        { "name": "author", "label": "Author", "widget": "string" },
        { "name": "body", "label": "Body", "widget": "markdown" },
        { "name": "featured_image", "label": "Featured Image", "widget": "image" }
      ]
    },
    {
      "name": "pages",
      "label": "Pages",
      "folder": "content/pages",
      "create": true,
      "fields": [
        { "name": "title", "label": "Title", "widget": "string" },
        { "name": "body", "label": "Body", "widget": "markdown" }
      ]
    }
  ],

  "accessControl": {
    "roles": [
      {
        "name": "admin",
        "permissions": ["create", "read", "update", "delete"]
      },
      {
        "name": "editor",
        "permissions": ["create", "read", "update"]
      }
    ]
  },
  "analytics": {
    "provider": "google",
    "trackingId": "UA-XXXXXXXXX-X"
  }
}
